version: '2.4'
services:
  pose:
    image: "pose_estimator"
    network_mode: "host"
    build: 
      context: ../../
      dockerfile: src/task/Dockerfile
    runtime: "nvidia"
    environment:
      ROS_MASTER_URI: "http://127.0.0.1:11311"
      ROS_IP: "127.0.0.1"
      DISPLAY: ${DISPLAY}
      Xvfb: 99 -screen 0 1920x1080x24
      QT_X11_NO_MITSHM: 1 

    command: bash -c "source /task/catkin_ws/devel/setup.bash; 
                      rosparam load  /config/params.yaml /pose_estimator;
                      ROS_NAMESPACE=pose_estimator python /task/src/ros_grasp_object.py"
    stdin_open: true
    tty: true

  yolov5:
    image: yolov5
    privileged: true
    build:
      context: ../../src/yolov5/docker/ycbv_segmentation_service
      dockerfile: dockerfile
    network_mode: "host"
    runtime: "nvidia"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../../src/yolov5:/root/yolo
    environment:
      - ROS_MASTER_URI=http://127.0.0.1:11311
      - ROS_IP=127.0.0.1
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    command: bash -c "source catkin_ws/devel/setup.bash; ROS_NAMESPACE=pose_estimator python ./yolo/detect_ros_seg.py --weights ./yolo/yolov5_ycbv_weights.pt --data ./yolo/data/ycbv.yaml --camera-topic "$(rosparam get /pose_estimator/camera_info_topic)""
    stdin_open: true
    tty: true 

  gdrnpp:
    image: gdrnpp
    build:
      context: ../../src/gdrnpp/docker
      dockerfile: dockerfile_ros
    network_mode: "host"
    runtime: "nvidia"
    volumes:
      - "../../src/gdrnpp:/root/gdrnpp:rw"
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ROS_MASTER_URI=http://127.0.0.1:11311
      - ROS_IP=127.0.0.1
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    command: bash -c "source catkin_ws/devel/setup.bash; ROS_NAMESPACE=pose_estimator python ./gdrnpp/core/gdrn_modeling/demo/demo_gdrn_ros.py"        
    stdin_open: true
    tty: true